// this file is auto generated by Makefile
#define SLS_USE_ASAN
#define SLS_USE_INT_AS_LONG
#define SLS_USE_CBLAS
#define SLS_USE_LAPACKE
#define SLS_USE_BOOST
#define SLS_USE_GSL
#define SLS_USE_EIGEN
#define SLS_USE_ARB
#define SLS_USE_ARPACK
#define SLS_USE_SQLITECPP
#define SLS_USE_SQLITE
