// this file is auto generated by Makefile/CMake
#define SLS_MAJOR 0
#define SLS_MINOR 3
#define SLS_PATCH 2
#define SLS_USE_ASAN
#define SLS_CHECK_BOUNDS
#define SLS_CHECK_SHAPES
#define SLS_USE_INT_AS_LONG
#define SLS_FP_EXCEPT
#define SLS_USE_UTFCPP
