function ret = same_shape(v1, v2, v3)
newline = char(10);
if nargin == 2
    ret = [
    '#ifdef SLS_CHECK_SHAPES' newline ...
    '    if (!shape_cmp(' v1 ', ' v2 '))' newline ...
    '        SLS_ERR("wrong shape!");' newline ...
    '#endif'
    ];
elseif nargin == 3
    ret = [
    '#ifdef SLS_CHECK_SHAPES' newline ...
    '    if (!shape_cmp(' v1 ', ' v2 ') || !shape_cmp(' v1 ', ' v3 '))' newline ...
    '        SLS_ERR("wrong shape!");' newline ...
    '#endif'
    ];
end
end
