# To build docker image, use `sudo docker build -t slisc0 -f Dockerfile_XXX .`
# To run test, use `sudo docker run slisc0`
# To open a bash, use `sudo docker run -it slisc0 bash`
# more docker commands https://wuli.wiki/online/Docker.html

FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt -y update && \
	apt -y upgrade && \
	apt install -y vim git make g++ gdb gfortran wget automake

# set your timezone
# set your timezone
RUN apt install -y tzdata
ENV TZ America/Chicago
RUN echo "${TZ}" > /etc/timezone \
  && ln -sf /usr/share/zoneinfo/America/Chicago /etc/localtime \
  && dpkg-reconfigure -f noninteractive tzdata

RUN cd /root/ && \
	wget https://github.com/xianyi/OpenBLAS/releases/download/v0.3.21/OpenBLAS-0.3.21.tar.gz && \
	tar -xzf OpenBLAS-0.3.21.tar.gz

RUN cd /root/OpenBLAS-0.3.21/ && \
	make USE_THREAD=0 -j12  && \
	make install

RUN	cd /root/ && \
	git clone --depth 1 https://github.com/MacroUniverse/SLISC0 && \
	git clone --depth 1 --branch long64-quad https://github.com/MacroUniverse/SLISC0 SLISC0-long64-quad

RUN cd /root/SLISC0 && \
	
