# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/addis/Documents/GitHub/SLISC0

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/addis/Documents/GitHub/SLISC0

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/addis/Documents/GitHub/SLISC0/CMakeFiles /mnt/c/Users/addis/Documents/GitHub/SLISC0/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/addis/Documents/GitHub/SLISC0/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main.x

# Build rule for target.
main.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main.x
.PHONY : main.x

# fast build rule for target.
main.x/fast:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/build
.PHONY : main.x/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/main.cpp.s
.PHONY : main.cpp.s

test/test_Bit.o: test/test_Bit.cpp.o

.PHONY : test/test_Bit.o

# target to build an object file
test/test_Bit.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Bit.cpp.o
.PHONY : test/test_Bit.cpp.o

test/test_Bit.i: test/test_Bit.cpp.i

.PHONY : test/test_Bit.i

# target to preprocess a source file
test/test_Bit.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Bit.cpp.i
.PHONY : test/test_Bit.cpp.i

test/test_Bit.s: test/test_Bit.cpp.s

.PHONY : test/test_Bit.s

# target to generate assembly for a file
test/test_Bit.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Bit.cpp.s
.PHONY : test/test_Bit.cpp.s

test/test_Cmat.o: test/test_Cmat.cpp.o

.PHONY : test/test_Cmat.o

# target to build an object file
test/test_Cmat.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Cmat.cpp.o
.PHONY : test/test_Cmat.cpp.o

test/test_Cmat.i: test/test_Cmat.cpp.i

.PHONY : test/test_Cmat.i

# target to preprocess a source file
test/test_Cmat.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Cmat.cpp.i
.PHONY : test/test_Cmat.cpp.i

test/test_Cmat.s: test/test_Cmat.cpp.s

.PHONY : test/test_Cmat.s

# target to generate assembly for a file
test/test_Cmat.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Cmat.cpp.s
.PHONY : test/test_Cmat.cpp.s

test/test_Cmat3.o: test/test_Cmat3.cpp.o

.PHONY : test/test_Cmat3.o

# target to build an object file
test/test_Cmat3.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Cmat3.cpp.o
.PHONY : test/test_Cmat3.cpp.o

test/test_Cmat3.i: test/test_Cmat3.cpp.i

.PHONY : test/test_Cmat3.i

# target to preprocess a source file
test/test_Cmat3.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Cmat3.cpp.i
.PHONY : test/test_Cmat3.cpp.i

test/test_Cmat3.s: test/test_Cmat3.cpp.s

.PHONY : test/test_Cmat3.s

# target to generate assembly for a file
test/test_Cmat3.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Cmat3.cpp.s
.PHONY : test/test_Cmat3.cpp.s

test/test_Cmat4.o: test/test_Cmat4.cpp.o

.PHONY : test/test_Cmat4.o

# target to build an object file
test/test_Cmat4.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Cmat4.cpp.o
.PHONY : test/test_Cmat4.cpp.o

test/test_Cmat4.i: test/test_Cmat4.cpp.i

.PHONY : test/test_Cmat4.i

# target to preprocess a source file
test/test_Cmat4.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Cmat4.cpp.i
.PHONY : test/test_Cmat4.cpp.i

test/test_Cmat4.s: test/test_Cmat4.cpp.s

.PHONY : test/test_Cmat4.s

# target to generate assembly for a file
test/test_Cmat4.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Cmat4.cpp.s
.PHONY : test/test_Cmat4.cpp.s

test/test_Cmobd.o: test/test_Cmobd.cpp.o

.PHONY : test/test_Cmobd.o

# target to build an object file
test/test_Cmobd.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Cmobd.cpp.o
.PHONY : test/test_Cmobd.cpp.o

test/test_Cmobd.i: test/test_Cmobd.cpp.i

.PHONY : test/test_Cmobd.i

# target to preprocess a source file
test/test_Cmobd.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Cmobd.cpp.i
.PHONY : test/test_Cmobd.cpp.i

test/test_Cmobd.s: test/test_Cmobd.cpp.s

.PHONY : test/test_Cmobd.s

# target to generate assembly for a file
test/test_Cmobd.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Cmobd.cpp.s
.PHONY : test/test_Cmobd.cpp.s

test/test_Dcmat.o: test/test_Dcmat.cpp.o

.PHONY : test/test_Dcmat.o

# target to build an object file
test/test_Dcmat.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Dcmat.cpp.o
.PHONY : test/test_Dcmat.cpp.o

test/test_Dcmat.i: test/test_Dcmat.cpp.i

.PHONY : test/test_Dcmat.i

# target to preprocess a source file
test/test_Dcmat.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Dcmat.cpp.i
.PHONY : test/test_Dcmat.cpp.i

test/test_Dcmat.s: test/test_Dcmat.cpp.s

.PHONY : test/test_Dcmat.s

# target to generate assembly for a file
test/test_Dcmat.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Dcmat.cpp.s
.PHONY : test/test_Dcmat.cpp.s

test/test_Dvec.o: test/test_Dvec.cpp.o

.PHONY : test/test_Dvec.o

# target to build an object file
test/test_Dvec.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Dvec.cpp.o
.PHONY : test/test_Dvec.cpp.o

test/test_Dvec.i: test/test_Dvec.cpp.i

.PHONY : test/test_Dvec.i

# target to preprocess a source file
test/test_Dvec.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Dvec.cpp.i
.PHONY : test/test_Dvec.cpp.i

test/test_Dvec.s: test/test_Dvec.cpp.s

.PHONY : test/test_Dvec.s

# target to generate assembly for a file
test/test_Dvec.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Dvec.cpp.s
.PHONY : test/test_Dvec.cpp.s

test/test_Imag.o: test/test_Imag.cpp.o

.PHONY : test/test_Imag.o

# target to build an object file
test/test_Imag.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Imag.cpp.o
.PHONY : test/test_Imag.cpp.o

test/test_Imag.i: test/test_Imag.cpp.i

.PHONY : test/test_Imag.i

# target to preprocess a source file
test/test_Imag.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Imag.cpp.i
.PHONY : test/test_Imag.cpp.i

test/test_Imag.s: test/test_Imag.cpp.s

.PHONY : test/test_Imag.s

# target to generate assembly for a file
test/test_Imag.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Imag.cpp.s
.PHONY : test/test_Imag.cpp.s

test/test_Mat.o: test/test_Mat.cpp.o

.PHONY : test/test_Mat.o

# target to build an object file
test/test_Mat.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Mat.cpp.o
.PHONY : test/test_Mat.cpp.o

test/test_Mat.i: test/test_Mat.cpp.i

.PHONY : test/test_Mat.i

# target to preprocess a source file
test/test_Mat.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Mat.cpp.i
.PHONY : test/test_Mat.cpp.i

test/test_Mat.s: test/test_Mat.cpp.s

.PHONY : test/test_Mat.s

# target to generate assembly for a file
test/test_Mat.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Mat.cpp.s
.PHONY : test/test_Mat.cpp.s

test/test_Mcoo.o: test/test_Mcoo.cpp.o

.PHONY : test/test_Mcoo.o

# target to build an object file
test/test_Mcoo.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Mcoo.cpp.o
.PHONY : test/test_Mcoo.cpp.o

test/test_Mcoo.i: test/test_Mcoo.cpp.i

.PHONY : test/test_Mcoo.i

# target to preprocess a source file
test/test_Mcoo.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Mcoo.cpp.i
.PHONY : test/test_Mcoo.cpp.i

test/test_Mcoo.s: test/test_Mcoo.cpp.s

.PHONY : test/test_Mcoo.s

# target to generate assembly for a file
test/test_Mcoo.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Mcoo.cpp.s
.PHONY : test/test_Mcoo.cpp.s

test/test_Scmat.o: test/test_Scmat.cpp.o

.PHONY : test/test_Scmat.o

# target to build an object file
test/test_Scmat.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Scmat.cpp.o
.PHONY : test/test_Scmat.cpp.o

test/test_Scmat.i: test/test_Scmat.cpp.i

.PHONY : test/test_Scmat.i

# target to preprocess a source file
test/test_Scmat.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Scmat.cpp.i
.PHONY : test/test_Scmat.cpp.i

test/test_Scmat.s: test/test_Scmat.cpp.s

.PHONY : test/test_Scmat.s

# target to generate assembly for a file
test/test_Scmat.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Scmat.cpp.s
.PHONY : test/test_Scmat.cpp.s

test/test_Scmat3.o: test/test_Scmat3.cpp.o

.PHONY : test/test_Scmat3.o

# target to build an object file
test/test_Scmat3.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Scmat3.cpp.o
.PHONY : test/test_Scmat3.cpp.o

test/test_Scmat3.i: test/test_Scmat3.cpp.i

.PHONY : test/test_Scmat3.i

# target to preprocess a source file
test/test_Scmat3.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Scmat3.cpp.i
.PHONY : test/test_Scmat3.cpp.i

test/test_Scmat3.s: test/test_Scmat3.cpp.s

.PHONY : test/test_Scmat3.s

# target to generate assembly for a file
test/test_Scmat3.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Scmat3.cpp.s
.PHONY : test/test_Scmat3.cpp.s

test/test_Svec.o: test/test_Svec.cpp.o

.PHONY : test/test_Svec.o

# target to build an object file
test/test_Svec.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Svec.cpp.o
.PHONY : test/test_Svec.cpp.o

test/test_Svec.i: test/test_Svec.cpp.i

.PHONY : test/test_Svec.i

# target to preprocess a source file
test/test_Svec.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Svec.cpp.i
.PHONY : test/test_Svec.cpp.i

test/test_Svec.s: test/test_Svec.cpp.s

.PHONY : test/test_Svec.s

# target to generate assembly for a file
test/test_Svec.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Svec.cpp.s
.PHONY : test/test_Svec.cpp.s

test/test_Vbase.o: test/test_Vbase.cpp.o

.PHONY : test/test_Vbase.o

# target to build an object file
test/test_Vbase.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Vbase.cpp.o
.PHONY : test/test_Vbase.cpp.o

test/test_Vbase.i: test/test_Vbase.cpp.i

.PHONY : test/test_Vbase.i

# target to preprocess a source file
test/test_Vbase.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Vbase.cpp.i
.PHONY : test/test_Vbase.cpp.i

test/test_Vbase.s: test/test_Vbase.cpp.s

.PHONY : test/test_Vbase.s

# target to generate assembly for a file
test/test_Vbase.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Vbase.cpp.s
.PHONY : test/test_Vbase.cpp.s

test/test_Vec.o: test/test_Vec.cpp.o

.PHONY : test/test_Vec.o

# target to build an object file
test/test_Vec.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Vec.cpp.o
.PHONY : test/test_Vec.cpp.o

test/test_Vec.i: test/test_Vec.cpp.i

.PHONY : test/test_Vec.i

# target to preprocess a source file
test/test_Vec.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Vec.cpp.i
.PHONY : test/test_Vec.cpp.i

test/test_Vec.s: test/test_Vec.cpp.s

.PHONY : test/test_Vec.s

# target to generate assembly for a file
test/test_Vec.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_Vec.cpp.s
.PHONY : test/test_Vec.cpp.s

test/test_anglib.o: test/test_anglib.cpp.o

.PHONY : test/test_anglib.o

# target to build an object file
test/test_anglib.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_anglib.cpp.o
.PHONY : test/test_anglib.cpp.o

test/test_anglib.i: test/test_anglib.cpp.i

.PHONY : test/test_anglib.i

# target to preprocess a source file
test/test_anglib.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_anglib.cpp.i
.PHONY : test/test_anglib.cpp.i

test/test_anglib.s: test/test_anglib.cpp.s

.PHONY : test/test_anglib.s

# target to generate assembly for a file
test/test_anglib.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_anglib.cpp.s
.PHONY : test/test_anglib.cpp.s

test/test_arb.o: test/test_arb.cpp.o

.PHONY : test/test_arb.o

# target to build an object file
test/test_arb.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_arb.cpp.o
.PHONY : test/test_arb.cpp.o

test/test_arb.i: test/test_arb.cpp.i

.PHONY : test/test_arb.i

# target to preprocess a source file
test/test_arb.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_arb.cpp.i
.PHONY : test/test_arb.cpp.i

test/test_arb.s: test/test_arb.cpp.s

.PHONY : test/test_arb.s

# target to generate assembly for a file
test/test_arb.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_arb.cpp.s
.PHONY : test/test_arb.cpp.s

test/test_arithmetic.o: test/test_arithmetic.cpp.o

.PHONY : test/test_arithmetic.o

# target to build an object file
test/test_arithmetic.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_arithmetic.cpp.o
.PHONY : test/test_arithmetic.cpp.o

test/test_arithmetic.i: test/test_arithmetic.cpp.i

.PHONY : test/test_arithmetic.i

# target to preprocess a source file
test/test_arithmetic.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_arithmetic.cpp.i
.PHONY : test/test_arithmetic.cpp.i

test/test_arithmetic.s: test/test_arithmetic.cpp.s

.PHONY : test/test_arithmetic.s

# target to generate assembly for a file
test/test_arithmetic.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_arithmetic.cpp.s
.PHONY : test/test_arithmetic.cpp.s

test/test_arpack.o: test/test_arpack.cpp.o

.PHONY : test/test_arpack.o

# target to build an object file
test/test_arpack.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_arpack.cpp.o
.PHONY : test/test_arpack.cpp.o

test/test_arpack.i: test/test_arpack.cpp.i

.PHONY : test/test_arpack.i

# target to preprocess a source file
test/test_arpack.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_arpack.cpp.i
.PHONY : test/test_arpack.cpp.i

test/test_arpack.s: test/test_arpack.cpp.s

.PHONY : test/test_arpack.s

# target to generate assembly for a file
test/test_arpack.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_arpack.cpp.s
.PHONY : test/test_arpack.cpp.s

test/test_band.o: test/test_band.cpp.o

.PHONY : test/test_band.o

# target to build an object file
test/test_band.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_band.cpp.o
.PHONY : test/test_band.cpp.o

test/test_band.i: test/test_band.cpp.i

.PHONY : test/test_band.i

# target to preprocess a source file
test/test_band.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_band.cpp.i
.PHONY : test/test_band.cpp.i

test/test_band.s: test/test_band.cpp.s

.PHONY : test/test_band.s

# target to generate assembly for a file
test/test_band.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_band.cpp.s
.PHONY : test/test_band.cpp.s

test/test_bin_tree.o: test/test_bin_tree.cpp.o

.PHONY : test/test_bin_tree.o

# target to build an object file
test/test_bin_tree.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_bin_tree.cpp.o
.PHONY : test/test_bin_tree.cpp.o

test/test_bin_tree.i: test/test_bin_tree.cpp.i

.PHONY : test/test_bin_tree.i

# target to preprocess a source file
test/test_bin_tree.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_bin_tree.cpp.i
.PHONY : test/test_bin_tree.cpp.i

test/test_bin_tree.s: test/test_bin_tree.cpp.s

.PHONY : test/test_bin_tree.s

# target to generate assembly for a file
test/test_bin_tree.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_bin_tree.cpp.s
.PHONY : test/test_bin_tree.cpp.s

test/test_bisection.o: test/test_bisection.cpp.o

.PHONY : test/test_bisection.o

# target to build an object file
test/test_bisection.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_bisection.cpp.o
.PHONY : test/test_bisection.cpp.o

test/test_bisection.i: test/test_bisection.cpp.i

.PHONY : test/test_bisection.i

# target to preprocess a source file
test/test_bisection.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_bisection.cpp.i
.PHONY : test/test_bisection.cpp.i

test/test_bisection.s: test/test_bisection.cpp.s

.PHONY : test/test_bisection.s

# target to generate assembly for a file
test/test_bisection.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_bisection.cpp.s
.PHONY : test/test_bisection.cpp.s

test/test_boost.o: test/test_boost.cpp.o

.PHONY : test/test_boost.o

# target to build an object file
test/test_boost.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_boost.cpp.o
.PHONY : test/test_boost.cpp.o

test/test_boost.i: test/test_boost.cpp.i

.PHONY : test/test_boost.i

# target to preprocess a source file
test/test_boost.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_boost.cpp.i
.PHONY : test/test_boost.cpp.i

test/test_boost.s: test/test_boost.cpp.s

.PHONY : test/test_boost.s

# target to generate assembly for a file
test/test_boost.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_boost.cpp.s
.PHONY : test/test_boost.cpp.s

test/test_compare.o: test/test_compare.cpp.o

.PHONY : test/test_compare.o

# target to build an object file
test/test_compare.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_compare.cpp.o
.PHONY : test/test_compare.cpp.o

test/test_compare.i: test/test_compare.cpp.i

.PHONY : test/test_compare.i

# target to preprocess a source file
test/test_compare.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_compare.cpp.i
.PHONY : test/test_compare.cpp.i

test/test_compare.s: test/test_compare.cpp.s

.PHONY : test/test_compare.s

# target to generate assembly for a file
test/test_compare.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_compare.cpp.s
.PHONY : test/test_compare.cpp.s

test/test_complex_arith.o: test/test_complex_arith.cpp.o

.PHONY : test/test_complex_arith.o

# target to build an object file
test/test_complex_arith.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_complex_arith.cpp.o
.PHONY : test/test_complex_arith.cpp.o

test/test_complex_arith.i: test/test_complex_arith.cpp.i

.PHONY : test/test_complex_arith.i

# target to preprocess a source file
test/test_complex_arith.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_complex_arith.cpp.i
.PHONY : test/test_complex_arith.cpp.i

test/test_complex_arith.s: test/test_complex_arith.cpp.s

.PHONY : test/test_complex_arith.s

# target to generate assembly for a file
test/test_complex_arith.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_complex_arith.cpp.s
.PHONY : test/test_complex_arith.cpp.s

test/test_copy.o: test/test_copy.cpp.o

.PHONY : test/test_copy.o

# target to build an object file
test/test_copy.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_copy.cpp.o
.PHONY : test/test_copy.cpp.o

test/test_copy.i: test/test_copy.cpp.i

.PHONY : test/test_copy.i

# target to preprocess a source file
test/test_copy.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_copy.cpp.i
.PHONY : test/test_copy.cpp.i

test/test_copy.s: test/test_copy.cpp.s

.PHONY : test/test_copy.s

# target to generate assembly for a file
test/test_copy.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_copy.cpp.s
.PHONY : test/test_copy.cpp.s

test/test_coulomb.o: test/test_coulomb.cpp.o

.PHONY : test/test_coulomb.o

# target to build an object file
test/test_coulomb.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_coulomb.cpp.o
.PHONY : test/test_coulomb.cpp.o

test/test_coulomb.i: test/test_coulomb.cpp.i

.PHONY : test/test_coulomb.i

# target to preprocess a source file
test/test_coulomb.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_coulomb.cpp.i
.PHONY : test/test_coulomb.cpp.i

test/test_coulomb.s: test/test_coulomb.cpp.s

.PHONY : test/test_coulomb.s

# target to generate assembly for a file
test/test_coulomb.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_coulomb.cpp.s
.PHONY : test/test_coulomb.cpp.s

test/test_cpp11.o: test/test_cpp11.cpp.o

.PHONY : test/test_cpp11.o

# target to build an object file
test/test_cpp11.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_cpp11.cpp.o
.PHONY : test/test_cpp11.cpp.o

test/test_cpp11.i: test/test_cpp11.cpp.i

.PHONY : test/test_cpp11.i

# target to preprocess a source file
test/test_cpp11.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_cpp11.cpp.i
.PHONY : test/test_cpp11.cpp.i

test/test_cpp11.s: test/test_cpp11.cpp.s

.PHONY : test/test_cpp11.s

# target to generate assembly for a file
test/test_cpp11.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_cpp11.cpp.s
.PHONY : test/test_cpp11.cpp.s

test/test_cut.o: test/test_cut.cpp.o

.PHONY : test/test_cut.o

# target to build an object file
test/test_cut.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_cut.cpp.o
.PHONY : test/test_cut.cpp.o

test/test_cut.i: test/test_cut.cpp.i

.PHONY : test/test_cut.i

# target to preprocess a source file
test/test_cut.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_cut.cpp.i
.PHONY : test/test_cut.cpp.i

test/test_cut.s: test/test_cut.cpp.s

.PHONY : test/test_cut.s

# target to generate assembly for a file
test/test_cut.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_cut.cpp.s
.PHONY : test/test_cut.cpp.s

test/test_dense.o: test/test_dense.cpp.o

.PHONY : test/test_dense.o

# target to build an object file
test/test_dense.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_dense.cpp.o
.PHONY : test/test_dense.cpp.o

test/test_dense.i: test/test_dense.cpp.i

.PHONY : test/test_dense.i

# target to preprocess a source file
test/test_dense.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_dense.cpp.i
.PHONY : test/test_dense.cpp.i

test/test_dense.s: test/test_dense.cpp.s

.PHONY : test/test_dense.s

# target to generate assembly for a file
test/test_dense.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_dense.cpp.s
.PHONY : test/test_dense.cpp.s

test/test_disp.o: test/test_disp.cpp.o

.PHONY : test/test_disp.o

# target to build an object file
test/test_disp.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_disp.cpp.o
.PHONY : test/test_disp.cpp.o

test/test_disp.i: test/test_disp.cpp.i

.PHONY : test/test_disp.i

# target to preprocess a source file
test/test_disp.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_disp.cpp.i
.PHONY : test/test_disp.cpp.i

test/test_disp.s: test/test_disp.cpp.s

.PHONY : test/test_disp.s

# target to generate assembly for a file
test/test_disp.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_disp.cpp.s
.PHONY : test/test_disp.cpp.s

test/test_eig.o: test/test_eig.cpp.o

.PHONY : test/test_eig.o

# target to build an object file
test/test_eig.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_eig.cpp.o
.PHONY : test/test_eig.cpp.o

test/test_eig.i: test/test_eig.cpp.i

.PHONY : test/test_eig.i

# target to preprocess a source file
test/test_eig.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_eig.cpp.i
.PHONY : test/test_eig.cpp.i

test/test_eig.s: test/test_eig.cpp.s

.PHONY : test/test_eig.s

# target to generate assembly for a file
test/test_eig.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_eig.cpp.s
.PHONY : test/test_eig.cpp.s

test/test_eigen.o: test/test_eigen.cpp.o

.PHONY : test/test_eigen.o

# target to build an object file
test/test_eigen.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_eigen.cpp.o
.PHONY : test/test_eigen.cpp.o

test/test_eigen.i: test/test_eigen.cpp.i

.PHONY : test/test_eigen.i

# target to preprocess a source file
test/test_eigen.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_eigen.cpp.i
.PHONY : test/test_eigen.cpp.i

test/test_eigen.s: test/test_eigen.cpp.s

.PHONY : test/test_eigen.s

# target to generate assembly for a file
test/test_eigen.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_eigen.cpp.s
.PHONY : test/test_eigen.cpp.s

test/test_expokit.o: test/test_expokit.cpp.o

.PHONY : test/test_expokit.o

# target to build an object file
test/test_expokit.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_expokit.cpp.o
.PHONY : test/test_expokit.cpp.o

test/test_expokit.i: test/test_expokit.cpp.i

.PHONY : test/test_expokit.i

# target to preprocess a source file
test/test_expokit.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_expokit.cpp.i
.PHONY : test/test_expokit.cpp.i

test/test_expokit.s: test/test_expokit.cpp.s

.PHONY : test/test_expokit.s

# target to generate assembly for a file
test/test_expokit.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_expokit.cpp.s
.PHONY : test/test_expokit.cpp.s

test/test_fedvr.o: test/test_fedvr.cpp.o

.PHONY : test/test_fedvr.o

# target to build an object file
test/test_fedvr.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_fedvr.cpp.o
.PHONY : test/test_fedvr.cpp.o

test/test_fedvr.i: test/test_fedvr.cpp.i

.PHONY : test/test_fedvr.i

# target to preprocess a source file
test/test_fedvr.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_fedvr.cpp.i
.PHONY : test/test_fedvr.cpp.i

test/test_fedvr.s: test/test_fedvr.cpp.s

.PHONY : test/test_fedvr.s

# target to generate assembly for a file
test/test_fedvr.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_fedvr.cpp.s
.PHONY : test/test_fedvr.cpp.s

test/test_fft.o: test/test_fft.cpp.o

.PHONY : test/test_fft.o

# target to build an object file
test/test_fft.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_fft.cpp.o
.PHONY : test/test_fft.cpp.o

test/test_fft.i: test/test_fft.cpp.i

.PHONY : test/test_fft.i

# target to preprocess a source file
test/test_fft.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_fft.cpp.i
.PHONY : test/test_fft.cpp.i

test/test_fft.s: test/test_fft.cpp.s

.PHONY : test/test_fft.s

# target to generate assembly for a file
test/test_fft.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_fft.cpp.s
.PHONY : test/test_fft.cpp.s

test/test_file.o: test/test_file.cpp.o

.PHONY : test/test_file.o

# target to build an object file
test/test_file.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_file.cpp.o
.PHONY : test/test_file.cpp.o

test/test_file.i: test/test_file.cpp.i

.PHONY : test/test_file.i

# target to preprocess a source file
test/test_file.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_file.cpp.i
.PHONY : test/test_file.cpp.i

test/test_file.s: test/test_file.cpp.s

.PHONY : test/test_file.s

# target to generate assembly for a file
test/test_file.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_file.cpp.s
.PHONY : test/test_file.cpp.s

test/test_global.o: test/test_global.cpp.o

.PHONY : test/test_global.o

# target to build an object file
test/test_global.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_global.cpp.o
.PHONY : test/test_global.cpp.o

test/test_global.i: test/test_global.cpp.i

.PHONY : test/test_global.i

# target to preprocess a source file
test/test_global.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_global.cpp.i
.PHONY : test/test_global.cpp.i

test/test_global.s: test/test_global.cpp.s

.PHONY : test/test_global.s

# target to generate assembly for a file
test/test_global.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_global.cpp.s
.PHONY : test/test_global.cpp.s

test/test_gsl.o: test/test_gsl.cpp.o

.PHONY : test/test_gsl.o

# target to build an object file
test/test_gsl.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_gsl.cpp.o
.PHONY : test/test_gsl.cpp.o

test/test_gsl.i: test/test_gsl.cpp.i

.PHONY : test/test_gsl.i

# target to preprocess a source file
test/test_gsl.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_gsl.cpp.i
.PHONY : test/test_gsl.cpp.i

test/test_gsl.s: test/test_gsl.cpp.s

.PHONY : test/test_gsl.s

# target to generate assembly for a file
test/test_gsl.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_gsl.cpp.s
.PHONY : test/test_gsl.cpp.s

test/test_hydrogen.o: test/test_hydrogen.cpp.o

.PHONY : test/test_hydrogen.o

# target to build an object file
test/test_hydrogen.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_hydrogen.cpp.o
.PHONY : test/test_hydrogen.cpp.o

test/test_hydrogen.i: test/test_hydrogen.cpp.i

.PHONY : test/test_hydrogen.i

# target to preprocess a source file
test/test_hydrogen.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_hydrogen.cpp.i
.PHONY : test/test_hydrogen.cpp.i

test/test_hydrogen.s: test/test_hydrogen.cpp.s

.PHONY : test/test_hydrogen.s

# target to generate assembly for a file
test/test_hydrogen.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_hydrogen.cpp.s
.PHONY : test/test_hydrogen.cpp.s

test/test_hypergeom.o: test/test_hypergeom.cpp.o

.PHONY : test/test_hypergeom.o

# target to build an object file
test/test_hypergeom.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_hypergeom.cpp.o
.PHONY : test/test_hypergeom.cpp.o

test/test_hypergeom.i: test/test_hypergeom.cpp.i

.PHONY : test/test_hypergeom.i

# target to preprocess a source file
test/test_hypergeom.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_hypergeom.cpp.i
.PHONY : test/test_hypergeom.cpp.i

test/test_hypergeom.s: test/test_hypergeom.cpp.s

.PHONY : test/test_hypergeom.s

# target to generate assembly for a file
test/test_hypergeom.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_hypergeom.cpp.s
.PHONY : test/test_hypergeom.cpp.s

test/test_input.o: test/test_input.cpp.o

.PHONY : test/test_input.o

# target to build an object file
test/test_input.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_input.cpp.o
.PHONY : test/test_input.cpp.o

test/test_input.i: test/test_input.cpp.i

.PHONY : test/test_input.i

# target to preprocess a source file
test/test_input.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_input.cpp.i
.PHONY : test/test_input.cpp.i

test/test_input.s: test/test_input.cpp.s

.PHONY : test/test_input.s

# target to generate assembly for a file
test/test_input.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_input.cpp.s
.PHONY : test/test_input.cpp.s

test/test_interp1.o: test/test_interp1.cpp.o

.PHONY : test/test_interp1.o

# target to build an object file
test/test_interp1.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_interp1.cpp.o
.PHONY : test/test_interp1.cpp.o

test/test_interp1.i: test/test_interp1.cpp.i

.PHONY : test/test_interp1.i

# target to preprocess a source file
test/test_interp1.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_interp1.cpp.i
.PHONY : test/test_interp1.cpp.i

test/test_interp1.s: test/test_interp1.cpp.s

.PHONY : test/test_interp1.s

# target to generate assembly for a file
test/test_interp1.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_interp1.cpp.s
.PHONY : test/test_interp1.cpp.s

test/test_lanczos.o: test/test_lanczos.cpp.o

.PHONY : test/test_lanczos.o

# target to build an object file
test/test_lanczos.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_lanczos.cpp.o
.PHONY : test/test_lanczos.cpp.o

test/test_lanczos.i: test/test_lanczos.cpp.i

.PHONY : test/test_lanczos.i

# target to preprocess a source file
test/test_lanczos.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_lanczos.cpp.i
.PHONY : test/test_lanczos.cpp.i

test/test_lanczos.s: test/test_lanczos.cpp.s

.PHONY : test/test_lanczos.s

# target to generate assembly for a file
test/test_lanczos.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_lanczos.cpp.s
.PHONY : test/test_lanczos.cpp.s

test/test_legendreP.o: test/test_legendreP.cpp.o

.PHONY : test/test_legendreP.o

# target to build an object file
test/test_legendreP.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_legendreP.cpp.o
.PHONY : test/test_legendreP.cpp.o

test/test_legendreP.i: test/test_legendreP.cpp.i

.PHONY : test/test_legendreP.i

# target to preprocess a source file
test/test_legendreP.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_legendreP.cpp.i
.PHONY : test/test_legendreP.cpp.i

test/test_legendreP.s: test/test_legendreP.cpp.s

.PHONY : test/test_legendreP.s

# target to generate assembly for a file
test/test_legendreP.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_legendreP.cpp.s
.PHONY : test/test_legendreP.cpp.s

test/test_lin_eq.o: test/test_lin_eq.cpp.o

.PHONY : test/test_lin_eq.o

# target to build an object file
test/test_lin_eq.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_lin_eq.cpp.o
.PHONY : test/test_lin_eq.cpp.o

test/test_lin_eq.i: test/test_lin_eq.cpp.i

.PHONY : test/test_lin_eq.i

# target to preprocess a source file
test/test_lin_eq.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_lin_eq.cpp.i
.PHONY : test/test_lin_eq.cpp.i

test/test_lin_eq.s: test/test_lin_eq.cpp.s

.PHONY : test/test_lin_eq.s

# target to generate assembly for a file
test/test_lin_eq.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_lin_eq.cpp.s
.PHONY : test/test_lin_eq.cpp.s

test/test_linbcg.o: test/test_linbcg.cpp.o

.PHONY : test/test_linbcg.o

# target to build an object file
test/test_linbcg.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_linbcg.cpp.o
.PHONY : test/test_linbcg.cpp.o

test/test_linbcg.i: test/test_linbcg.cpp.i

.PHONY : test/test_linbcg.i

# target to preprocess a source file
test/test_linbcg.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_linbcg.cpp.i
.PHONY : test/test_linbcg.cpp.i

test/test_linbcg.s: test/test_linbcg.cpp.s

.PHONY : test/test_linbcg.s

# target to generate assembly for a file
test/test_linbcg.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_linbcg.cpp.s
.PHONY : test/test_linbcg.cpp.s

test/test_linux.o: test/test_linux.cpp.o

.PHONY : test/test_linux.o

# target to build an object file
test/test_linux.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_linux.cpp.o
.PHONY : test/test_linux.cpp.o

test/test_linux.i: test/test_linux.cpp.i

.PHONY : test/test_linux.i

# target to preprocess a source file
test/test_linux.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_linux.cpp.i
.PHONY : test/test_linux.cpp.i

test/test_linux.s: test/test_linux.cpp.s

.PHONY : test/test_linux.s

# target to generate assembly for a file
test/test_linux.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_linux.cpp.s
.PHONY : test/test_linux.cpp.s

test/test_mat_fun.o: test/test_mat_fun.cpp.o

.PHONY : test/test_mat_fun.o

# target to build an object file
test/test_mat_fun.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_mat_fun.cpp.o
.PHONY : test/test_mat_fun.cpp.o

test/test_mat_fun.i: test/test_mat_fun.cpp.i

.PHONY : test/test_mat_fun.i

# target to preprocess a source file
test/test_mat_fun.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_mat_fun.cpp.i
.PHONY : test/test_mat_fun.cpp.i

test/test_mat_fun.s: test/test_mat_fun.cpp.s

.PHONY : test/test_mat_fun.s

# target to generate assembly for a file
test/test_mat_fun.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_mat_fun.cpp.s
.PHONY : test/test_mat_fun.cpp.s

test/test_matb.o: test/test_matb.cpp.o

.PHONY : test/test_matb.o

# target to build an object file
test/test_matb.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_matb.cpp.o
.PHONY : test/test_matb.cpp.o

test/test_matb.i: test/test_matb.cpp.i

.PHONY : test/test_matb.i

# target to preprocess a source file
test/test_matb.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_matb.cpp.i
.PHONY : test/test_matb.cpp.i

test/test_matb.s: test/test_matb.cpp.s

.PHONY : test/test_matb.s

# target to generate assembly for a file
test/test_matb.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_matb.cpp.s
.PHONY : test/test_matb.cpp.s

test/test_matfile.o: test/test_matfile.cpp.o

.PHONY : test/test_matfile.o

# target to build an object file
test/test_matfile.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_matfile.cpp.o
.PHONY : test/test_matfile.cpp.o

test/test_matfile.i: test/test_matfile.cpp.i

.PHONY : test/test_matfile.i

# target to preprocess a source file
test/test_matfile.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_matfile.cpp.i
.PHONY : test/test_matfile.cpp.i

test/test_matfile.s: test/test_matfile.cpp.s

.PHONY : test/test_matfile.s

# target to generate assembly for a file
test/test_matfile.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_matfile.cpp.s
.PHONY : test/test_matfile.cpp.s

test/test_matt.o: test/test_matt.cpp.o

.PHONY : test/test_matt.o

# target to build an object file
test/test_matt.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_matt.cpp.o
.PHONY : test/test_matt.cpp.o

test/test_matt.i: test/test_matt.cpp.i

.PHONY : test/test_matt.i

# target to preprocess a source file
test/test_matt.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_matt.cpp.i
.PHONY : test/test_matt.cpp.i

test/test_matt.s: test/test_matt.cpp.s

.PHONY : test/test_matt.s

# target to generate assembly for a file
test/test_matt.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_matt.cpp.s
.PHONY : test/test_matt.cpp.s

test/test_quad_math.o: test/test_quad_math.cpp.o

.PHONY : test/test_quad_math.o

# target to build an object file
test/test_quad_math.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_quad_math.cpp.o
.PHONY : test/test_quad_math.cpp.o

test/test_quad_math.i: test/test_quad_math.cpp.i

.PHONY : test/test_quad_math.i

# target to preprocess a source file
test/test_quad_math.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_quad_math.cpp.i
.PHONY : test/test_quad_math.cpp.i

test/test_quad_math.s: test/test_quad_math.cpp.s

.PHONY : test/test_quad_math.s

# target to generate assembly for a file
test/test_quad_math.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_quad_math.cpp.s
.PHONY : test/test_quad_math.cpp.s

test/test_random.o: test/test_random.cpp.o

.PHONY : test/test_random.o

# target to build an object file
test/test_random.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_random.cpp.o
.PHONY : test/test_random.cpp.o

test/test_random.i: test/test_random.cpp.i

.PHONY : test/test_random.i

# target to preprocess a source file
test/test_random.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_random.cpp.i
.PHONY : test/test_random.cpp.i

test/test_random.s: test/test_random.cpp.s

.PHONY : test/test_random.s

# target to generate assembly for a file
test/test_random.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_random.cpp.s
.PHONY : test/test_random.cpp.s

test/test_scalar_arith.o: test/test_scalar_arith.cpp.o

.PHONY : test/test_scalar_arith.o

# target to build an object file
test/test_scalar_arith.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_scalar_arith.cpp.o
.PHONY : test/test_scalar_arith.cpp.o

test/test_scalar_arith.i: test/test_scalar_arith.cpp.i

.PHONY : test/test_scalar_arith.i

# target to preprocess a source file
test/test_scalar_arith.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_scalar_arith.cpp.i
.PHONY : test/test_scalar_arith.cpp.i

test/test_scalar_arith.s: test/test_scalar_arith.cpp.s

.PHONY : test/test_scalar_arith.s

# target to generate assembly for a file
test/test_scalar_arith.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_scalar_arith.cpp.s
.PHONY : test/test_scalar_arith.cpp.s

test/test_search.o: test/test_search.cpp.o

.PHONY : test/test_search.o

# target to build an object file
test/test_search.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_search.cpp.o
.PHONY : test/test_search.cpp.o

test/test_search.i: test/test_search.cpp.i

.PHONY : test/test_search.i

# target to preprocess a source file
test/test_search.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_search.cpp.i
.PHONY : test/test_search.cpp.i

test/test_search.s: test/test_search.cpp.s

.PHONY : test/test_search.s

# target to generate assembly for a file
test/test_search.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_search.cpp.s
.PHONY : test/test_search.cpp.s

test/test_sha1sum.o: test/test_sha1sum.cpp.o

.PHONY : test/test_sha1sum.o

# target to build an object file
test/test_sha1sum.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_sha1sum.cpp.o
.PHONY : test/test_sha1sum.cpp.o

test/test_sha1sum.i: test/test_sha1sum.cpp.i

.PHONY : test/test_sha1sum.i

# target to preprocess a source file
test/test_sha1sum.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_sha1sum.cpp.i
.PHONY : test/test_sha1sum.cpp.i

test/test_sha1sum.s: test/test_sha1sum.cpp.s

.PHONY : test/test_sha1sum.s

# target to generate assembly for a file
test/test_sha1sum.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_sha1sum.cpp.s
.PHONY : test/test_sha1sum.cpp.s

test/test_sing_list.o: test/test_sing_list.cpp.o

.PHONY : test/test_sing_list.o

# target to build an object file
test/test_sing_list.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_sing_list.cpp.o
.PHONY : test/test_sing_list.cpp.o

test/test_sing_list.i: test/test_sing_list.cpp.i

.PHONY : test/test_sing_list.i

# target to preprocess a source file
test/test_sing_list.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_sing_list.cpp.i
.PHONY : test/test_sing_list.cpp.i

test/test_sing_list.s: test/test_sing_list.cpp.s

.PHONY : test/test_sing_list.s

# target to generate assembly for a file
test/test_sing_list.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_sing_list.cpp.s
.PHONY : test/test_sing_list.cpp.s

test/test_sort.o: test/test_sort.cpp.o

.PHONY : test/test_sort.o

# target to build an object file
test/test_sort.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_sort.cpp.o
.PHONY : test/test_sort.cpp.o

test/test_sort.i: test/test_sort.cpp.i

.PHONY : test/test_sort.i

# target to preprocess a source file
test/test_sort.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_sort.cpp.i
.PHONY : test/test_sort.cpp.i

test/test_sort.s: test/test_sort.cpp.s

.PHONY : test/test_sort.s

# target to generate assembly for a file
test/test_sort.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_sort.cpp.s
.PHONY : test/test_sort.cpp.s

test/test_sqlite.o: test/test_sqlite.cpp.o

.PHONY : test/test_sqlite.o

# target to build an object file
test/test_sqlite.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_sqlite.cpp.o
.PHONY : test/test_sqlite.cpp.o

test/test_sqlite.i: test/test_sqlite.cpp.i

.PHONY : test/test_sqlite.i

# target to preprocess a source file
test/test_sqlite.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_sqlite.cpp.i
.PHONY : test/test_sqlite.cpp.i

test/test_sqlite.s: test/test_sqlite.cpp.s

.PHONY : test/test_sqlite.s

# target to generate assembly for a file
test/test_sqlite.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_sqlite.cpp.s
.PHONY : test/test_sqlite.cpp.s

test/test_string.o: test/test_string.cpp.o

.PHONY : test/test_string.o

# target to build an object file
test/test_string.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_string.cpp.o
.PHONY : test/test_string.cpp.o

test/test_string.i: test/test_string.cpp.i

.PHONY : test/test_string.i

# target to preprocess a source file
test/test_string.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_string.cpp.i
.PHONY : test/test_string.cpp.i

test/test_string.s: test/test_string.cpp.s

.PHONY : test/test_string.s

# target to generate assembly for a file
test/test_string.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_string.cpp.s
.PHONY : test/test_string.cpp.s

test/test_time.o: test/test_time.cpp.o

.PHONY : test/test_time.o

# target to build an object file
test/test_time.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_time.cpp.o
.PHONY : test/test_time.cpp.o

test/test_time.i: test/test_time.cpp.i

.PHONY : test/test_time.i

# target to preprocess a source file
test/test_time.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_time.cpp.i
.PHONY : test/test_time.cpp.i

test/test_time.s: test/test_time.cpp.s

.PHONY : test/test_time.s

# target to generate assembly for a file
test/test_time.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_time.cpp.s
.PHONY : test/test_time.cpp.s

test/test_unicode.o: test/test_unicode.cpp.o

.PHONY : test/test_unicode.o

# target to build an object file
test/test_unicode.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_unicode.cpp.o
.PHONY : test/test_unicode.cpp.o

test/test_unicode.i: test/test_unicode.cpp.i

.PHONY : test/test_unicode.i

# target to preprocess a source file
test/test_unicode.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_unicode.cpp.i
.PHONY : test/test_unicode.cpp.i

test/test_unicode.s: test/test_unicode.cpp.s

.PHONY : test/test_unicode.s

# target to generate assembly for a file
test/test_unicode.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_unicode.cpp.s
.PHONY : test/test_unicode.cpp.s

test/test_ylm.o: test/test_ylm.cpp.o

.PHONY : test/test_ylm.o

# target to build an object file
test/test_ylm.cpp.o:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_ylm.cpp.o
.PHONY : test/test_ylm.cpp.o

test/test_ylm.i: test/test_ylm.cpp.i

.PHONY : test/test_ylm.i

# target to preprocess a source file
test/test_ylm.cpp.i:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_ylm.cpp.i
.PHONY : test/test_ylm.cpp.i

test/test_ylm.s: test/test_ylm.cpp.s

.PHONY : test/test_ylm.s

# target to generate assembly for a file
test/test_ylm.cpp.s:
	$(MAKE) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/test/test_ylm.cpp.s
.PHONY : test/test_ylm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main.x"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... test/test_Bit.o"
	@echo "... test/test_Bit.i"
	@echo "... test/test_Bit.s"
	@echo "... test/test_Cmat.o"
	@echo "... test/test_Cmat.i"
	@echo "... test/test_Cmat.s"
	@echo "... test/test_Cmat3.o"
	@echo "... test/test_Cmat3.i"
	@echo "... test/test_Cmat3.s"
	@echo "... test/test_Cmat4.o"
	@echo "... test/test_Cmat4.i"
	@echo "... test/test_Cmat4.s"
	@echo "... test/test_Cmobd.o"
	@echo "... test/test_Cmobd.i"
	@echo "... test/test_Cmobd.s"
	@echo "... test/test_Dcmat.o"
	@echo "... test/test_Dcmat.i"
	@echo "... test/test_Dcmat.s"
	@echo "... test/test_Dvec.o"
	@echo "... test/test_Dvec.i"
	@echo "... test/test_Dvec.s"
	@echo "... test/test_Imag.o"
	@echo "... test/test_Imag.i"
	@echo "... test/test_Imag.s"
	@echo "... test/test_Mat.o"
	@echo "... test/test_Mat.i"
	@echo "... test/test_Mat.s"
	@echo "... test/test_Mcoo.o"
	@echo "... test/test_Mcoo.i"
	@echo "... test/test_Mcoo.s"
	@echo "... test/test_Scmat.o"
	@echo "... test/test_Scmat.i"
	@echo "... test/test_Scmat.s"
	@echo "... test/test_Scmat3.o"
	@echo "... test/test_Scmat3.i"
	@echo "... test/test_Scmat3.s"
	@echo "... test/test_Svec.o"
	@echo "... test/test_Svec.i"
	@echo "... test/test_Svec.s"
	@echo "... test/test_Vbase.o"
	@echo "... test/test_Vbase.i"
	@echo "... test/test_Vbase.s"
	@echo "... test/test_Vec.o"
	@echo "... test/test_Vec.i"
	@echo "... test/test_Vec.s"
	@echo "... test/test_anglib.o"
	@echo "... test/test_anglib.i"
	@echo "... test/test_anglib.s"
	@echo "... test/test_arb.o"
	@echo "... test/test_arb.i"
	@echo "... test/test_arb.s"
	@echo "... test/test_arithmetic.o"
	@echo "... test/test_arithmetic.i"
	@echo "... test/test_arithmetic.s"
	@echo "... test/test_arpack.o"
	@echo "... test/test_arpack.i"
	@echo "... test/test_arpack.s"
	@echo "... test/test_band.o"
	@echo "... test/test_band.i"
	@echo "... test/test_band.s"
	@echo "... test/test_bin_tree.o"
	@echo "... test/test_bin_tree.i"
	@echo "... test/test_bin_tree.s"
	@echo "... test/test_bisection.o"
	@echo "... test/test_bisection.i"
	@echo "... test/test_bisection.s"
	@echo "... test/test_boost.o"
	@echo "... test/test_boost.i"
	@echo "... test/test_boost.s"
	@echo "... test/test_compare.o"
	@echo "... test/test_compare.i"
	@echo "... test/test_compare.s"
	@echo "... test/test_complex_arith.o"
	@echo "... test/test_complex_arith.i"
	@echo "... test/test_complex_arith.s"
	@echo "... test/test_copy.o"
	@echo "... test/test_copy.i"
	@echo "... test/test_copy.s"
	@echo "... test/test_coulomb.o"
	@echo "... test/test_coulomb.i"
	@echo "... test/test_coulomb.s"
	@echo "... test/test_cpp11.o"
	@echo "... test/test_cpp11.i"
	@echo "... test/test_cpp11.s"
	@echo "... test/test_cut.o"
	@echo "... test/test_cut.i"
	@echo "... test/test_cut.s"
	@echo "... test/test_dense.o"
	@echo "... test/test_dense.i"
	@echo "... test/test_dense.s"
	@echo "... test/test_disp.o"
	@echo "... test/test_disp.i"
	@echo "... test/test_disp.s"
	@echo "... test/test_eig.o"
	@echo "... test/test_eig.i"
	@echo "... test/test_eig.s"
	@echo "... test/test_eigen.o"
	@echo "... test/test_eigen.i"
	@echo "... test/test_eigen.s"
	@echo "... test/test_expokit.o"
	@echo "... test/test_expokit.i"
	@echo "... test/test_expokit.s"
	@echo "... test/test_fedvr.o"
	@echo "... test/test_fedvr.i"
	@echo "... test/test_fedvr.s"
	@echo "... test/test_fft.o"
	@echo "... test/test_fft.i"
	@echo "... test/test_fft.s"
	@echo "... test/test_file.o"
	@echo "... test/test_file.i"
	@echo "... test/test_file.s"
	@echo "... test/test_global.o"
	@echo "... test/test_global.i"
	@echo "... test/test_global.s"
	@echo "... test/test_gsl.o"
	@echo "... test/test_gsl.i"
	@echo "... test/test_gsl.s"
	@echo "... test/test_hydrogen.o"
	@echo "... test/test_hydrogen.i"
	@echo "... test/test_hydrogen.s"
	@echo "... test/test_hypergeom.o"
	@echo "... test/test_hypergeom.i"
	@echo "... test/test_hypergeom.s"
	@echo "... test/test_input.o"
	@echo "... test/test_input.i"
	@echo "... test/test_input.s"
	@echo "... test/test_interp1.o"
	@echo "... test/test_interp1.i"
	@echo "... test/test_interp1.s"
	@echo "... test/test_lanczos.o"
	@echo "... test/test_lanczos.i"
	@echo "... test/test_lanczos.s"
	@echo "... test/test_legendreP.o"
	@echo "... test/test_legendreP.i"
	@echo "... test/test_legendreP.s"
	@echo "... test/test_lin_eq.o"
	@echo "... test/test_lin_eq.i"
	@echo "... test/test_lin_eq.s"
	@echo "... test/test_linbcg.o"
	@echo "... test/test_linbcg.i"
	@echo "... test/test_linbcg.s"
	@echo "... test/test_linux.o"
	@echo "... test/test_linux.i"
	@echo "... test/test_linux.s"
	@echo "... test/test_mat_fun.o"
	@echo "... test/test_mat_fun.i"
	@echo "... test/test_mat_fun.s"
	@echo "... test/test_matb.o"
	@echo "... test/test_matb.i"
	@echo "... test/test_matb.s"
	@echo "... test/test_matfile.o"
	@echo "... test/test_matfile.i"
	@echo "... test/test_matfile.s"
	@echo "... test/test_matt.o"
	@echo "... test/test_matt.i"
	@echo "... test/test_matt.s"
	@echo "... test/test_quad_math.o"
	@echo "... test/test_quad_math.i"
	@echo "... test/test_quad_math.s"
	@echo "... test/test_random.o"
	@echo "... test/test_random.i"
	@echo "... test/test_random.s"
	@echo "... test/test_scalar_arith.o"
	@echo "... test/test_scalar_arith.i"
	@echo "... test/test_scalar_arith.s"
	@echo "... test/test_search.o"
	@echo "... test/test_search.i"
	@echo "... test/test_search.s"
	@echo "... test/test_sha1sum.o"
	@echo "... test/test_sha1sum.i"
	@echo "... test/test_sha1sum.s"
	@echo "... test/test_sing_list.o"
	@echo "... test/test_sing_list.i"
	@echo "... test/test_sing_list.s"
	@echo "... test/test_sort.o"
	@echo "... test/test_sort.i"
	@echo "... test/test_sort.s"
	@echo "... test/test_sqlite.o"
	@echo "... test/test_sqlite.i"
	@echo "... test/test_sqlite.s"
	@echo "... test/test_string.o"
	@echo "... test/test_string.i"
	@echo "... test/test_string.s"
	@echo "... test/test_time.o"
	@echo "... test/test_time.i"
	@echo "... test/test_time.s"
	@echo "... test/test_unicode.o"
	@echo "... test/test_unicode.i"
	@echo "... test/test_unicode.s"
	@echo "... test/test_ylm.o"
	@echo "... test/test_ylm.i"
	@echo "... test/test_ylm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

