--- SLISC0 SQLite data file for variables -----
--- similar to Matlab's mat file ---

CREATE TABLE VARS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT, -- never change once created
	NAME TEXT UNIQUE NOT NULL, -- can be renamed
	TYPE_NUM INTEGER NOT NULL, -- reference TYPES table
	SHAPE TEXT, -- e.g.  '10 20 30', NULL for scalar
	DATA BLOB, -- actual data, if NULL, then data is stored in another table named 'ID'
	FINISHED INTEGER, -- has all data finished writing?
	FOREIGN KEY (TYPE_NUM) REFERENCES TYPES (TYPE_NUM)
);

CREATE TABLE TYPES (
	TYPE_NUM INTEGER PRIMARY KEY, -- type number
	TYPE TEXT UNIQUE -- UCHAR, CHAR, UINT8, INT8, INT64 ... , SINGLE, DOUBLE ...
);

INSERT INTO TYPES VALUES (0, 'Bool');
INSERT INTO TYPES VALUES (1, 'Char');
INSERT INTO TYPES VALUES (2, 'Int32');
INSERT INTO TYPES VALUES (3, 'Int64');
INSERT INTO TYPES VALUES (21, 'Double');
INSERT INTO TYPES VALUES (41, 'Complex');
--- TODO: add more ---

----- Example Data -----

INSERT INTO VARS (NAME, TYPE_NUM, SHAPE, DATA, FINISHED) VALUES ('myInt32', 2, NULL, 'w82h', 0);
UPDATE VARS SET FINISHED = 1 WHERE NAME = 'myInt32';

INSERT INTO VARS (NAME, TYPE_NUM, SHAPE, DATA, FINISHED) VALUES ('myBool', 0, NULL, 'a', 0);
UPDATE VARS SET FINISHED = 1 WHERE NAME = 'myBool';

INSERT INTO VARS (NAME, TYPE_NUM, SHAPE, DATA, FINISHED) VALUES ('myDoub', 0, '2 4 3', 'a2d4q6f8e0w4r2h4k1h21q24', 0);
UPDATE VARS SET FINISHED = 1 WHERE NAME = 'myDoub';

INSERT INTO VARS (NAME, TYPE_NUM, SHAPE, DATA, FINISHED) VALUES ('myHuge', 0, '3 5 6 9 10 100', NULL, 0);
CREATE TABLE '4' ( -- extra table for 'myHuge'
	BLOCK_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	BLOCK BLOB
);
INSERT INTO '4' (BLOCK) VALUES ('1234567890');
INSERT INTO '4' (BLOCK) VALUES ('1234567890');
INSERT INTO '4' (BLOCK) VALUES ('1234567890');
INSERT INTO '4' (BLOCK) VALUES ('123');
UPDATE VARS SET FINISHED = 1 WHERE NAME = 'myHuge';

-- get size ---
-- SELECT LENGTH(BLOCK) FROM '4'
-- SELECT COUNT(*) FROM '4'
