FROM centos:7.9.2009
# don't modify anything in ~/.bashrc, there will be problem

RUN yum install -y https://repo.ius.io/ius-release-el7.rpm
RUN yum install -y centos-release-scl

# includes g++ and gfortran 9.3.1, GDB 8.3 make 4.2.1
# ref: https://access.redhat.com/documentation/en-us/red_hat_developer_toolset/9/html-single/user_guide/index
RUN yum install -y devtoolset-9

# this set the shel for rest of the Dockerfile, but not for `docker run`
# equivalent to `scl enable devtoolset-9 bash` in a bash session
SHELL [ "scl", "enable", "devtoolset-9" ]

RUN yum install -y git vim time \
	gmp-devel mpfr-devel soci-sqlite3-devel boost-filesystem wget mlocate

RUN	cd /root/ && \
	git clone https://github.com/MacroUniverse/SLISC0 --depth 1 && \
	git clone https://github.com/MacroUniverse/Arpack_test --depth 1 && \
	git clone https://github.com/MacroUniverse/EigenTest --depth 1 && \
	git clone https://github.com/MacroUniverse/boost-headers --depth 1 && \
	git clone https://github.com/MacroUniverse/GSL-2.5-test --depth 1 && \
	git clone https://github.com/fredrik-johansson/arb && \
	git clone https://github.com/fredrik-johansson/flint2 

# GSL
RUN	cd /root/GSL-2.5-test/gsl-2.5-original && \
	chmod +x ./configure && ./configure && \
	make -j12 && make install

# flint2
RUN cd /root/flint2/ && git checkout 14dc6cbd2 && \
	chmod +x ./configure && ./configure && \
	make -j12 && make install

# Arb
RUN cd /root/arb && git checkout 2.23.0 && \
	chmod +x ./configure && ./configure && \
	make -j12 && make install && \
	ln -s libarb.so /usr/local/lib/libflint-arb.so && \
	ldconfig

# CMake
RUN cd /root/ && \
	wget https://github.com/Kitware/CMake/releases/download/v3.25.0-rc4/cmake-3.25.0-rc4-linux-x86_64.tar.gz && \
	tar -xzf cmake-3.25.0-rc4-linux-x86_64.tar.gz && \
	ln -sf /root/cmake-3.25.0-rc4-linux-x86_64/bin/cmake /usr/bin/ && \
	rm cmake-3.25.0-rc4-linux-x86_64.tar.gz

# (C)BLAS and LAPACK(E) 64bit dynamic (reference)
RUN	cd /root/ && \
	wget https://github.com/Reference-LAPACK/lapack/archive/refs/tags/v3.10.1.tar.gz && \
	tar -xzf v3.10.1.tar.gz && \
	mkdir lapack-build && cd lapack-build && \
	cmake -DBUILD_INDEX64=ON -DBUILD_SHARED_LIBS=ON -DLAPACKE=ON -DCBLAS=ON  ../lapack-3.10.1/ && \
	cd /root/lapack-build && make -j12 && make install

# (C)BLAS and LAPACK(E) 32bit dynamic (reference)
RUN cd /root/ && \
	rm -rf lapack-3.10.1 && rm -rf lapack-build && \
	tar -xzf v3.10.1.tar.gz && \
	mkdir lapack-build && cd lapack-build && \
	cmake -DBUILD_INDEX64=OFF -DBUILD_SHARED_LIBS=ON -DLAPACKE=ON -DCBLAS=ON  ../lapack-3.10.1/ && \
	cd /root/lapack-build && make -j12 && make install

# (C)BLAS and LAPACK(E) 64bit static (reference)
RUN cd /root/ && \
	rm -rf lapack-3.10.1 && rm -rf lapack-build && \
	tar -xzf v3.10.1.tar.gz && \
	mkdir lapack-build && cd lapack-build && \
	cmake -DBUILD_INDEX64=ON -DBUILD_SHARED_LIBS=OFF -DLAPACKE=ON -DCBLAS=ON  ../lapack-3.10.1/ && \
	cd /root/lapack-build && make -j12 && make install

# (C)BLAS and LAPACK(E) 32bit static (reference)
RUN cd /root/ && \
	rm -rf lapack-3.10.1 && rm -rf lapack-build && \
	tar -xzf v3.10.1.tar.gz && \
	mkdir lapack-build && cd lapack-build && \
	cmake -DBUILD_INDEX64=OFF -DBUILD_SHARED_LIBS=OFF -DLAPACKE=ON -DCBLAS=ON  ../lapack-3.10.1/ && \
	cd /root/lapack-build && make -j12 && make install

RUN ln -s /usr/lib64/libboost_filesystem.so.* /usr/lib64/libboost_filesystem.so && \
	ln -s /usr/lib64/libboost_system.so.* /usr/lib64/libboost_system.so

RUN yum install -y automake libtool

# Arpack-NG
RUN source ~/SLISC0/make/ld_path_append.sh /usr/local/lib/ && \
	source ~/SLISC0/make/ld_path_append.sh /usr/local/lib64/ && \
	cd /root/ && \
	wget https://github.com/opencollab/arpack-ng/archive/refs/tags/3.8.0.tar.gz && \
	tar -xzf 3.8.0.tar.gz && cd arpack-ng-3.8.0 && \
	sh bootstrap && ./configure && make -j12 && make check && \
	make install

RUN yum install -y soci-sqlite3-devel

RUN cd /root/SLISC0 && \
	git pull origin && touch SLISC/*.h && \
	make -j12 opt_asan=false && \
	source ~/SLISC0/make/ld_path_append.sh /usr/local/lib/ && \
	source ~/SLISC0/make/ld_path_append.sh /usr/local/lib64/ && \
	./main.x < input.inp

RUN cd /root/SLISC0 && \
	cp SLISC-long64-quad/*.h SLISC/ && \
	make -j12 opt_long32=false opt_quadmath=true opt_asan=false && \
	source ~/SLISC0/make/ld_path_append.sh /usr/local/lib/ && \
	source ~/SLISC0/make/ld_path_append.sh /usr/local/lib64/ && \
	./main.x < input.inp

# set LD_LIBRARY_PATH
# bashrc doesn't work for `RUN` ! only for bash section
RUN echo "cd ~" >> ~/.bashrc && \
	echo "source ~/SLISC0/make/ld_path_append.sh /usr/local/lib/" >> ~/.bashrc && \
	echo "source ~/SLISC0/make/ld_path_append.sh /usr/local/lib64/" >> ~/.bashrc

# RUN echo "#! /usr/bin/bash" > /test.sh && \
#	echo "cd /root/SLISC0" >> /test.sh && \
#	echo "./main.x < input.inp" >> /test.sh && \
#	chmod +x /test.sh

# this doesn't work yet since we need to run `scl enable devtoolset-9 bash` first
# CMD ["/test.sh"]
