// this file is auto generated by Makefile/CMake
#define SLS_MAJOR 0
#define SLS_MINOR 3
#define SLS_PATCH 3
#define SLS_USE_ASAN
#define SLS_CHECK_BOUNDS
#define SLS_CHECK_SHAPES
#define SLS_USE_CBLAS
#define SLS_USE_LAPACKE
#define SLS_USE_BOOST
#define SLS_USE_GSL
#define SLS_USE_EIGEN
#define SLS_USE_QUAD_MATH
#define SLS_USE_ARB
#define SLS_USE_MPLAPACK
#define SLS_USE_ARPACK
#define SLS_USE_SQLITECPP
#define SLS_USE_SQLITE
#define SLS_USE_HDF
#define SLS_FP_EXCEPT
#define SLS_USE_UTFCPP
