// this file is auto generated by Makefile/CMake
#define SLS_MAJOR 0
#define SLS_MINOR 2
#define SLS_PATCH 7
#define SLS_CHECK_BOUNDS
#define SLS_CHECK_SHAPES
#define SLS_USE_ASAN
#define SLS_USE_QUAD_MATH
#define SLS_FP_EXCEPT
#define SLS_USE_UTFCPP
