cd(mfilepath);
file = 'global_contain_typedef.tp';
type = {
    {'Vbase', 'Char', 'Int', 'Llong', 'Long', 'Fdoub', ...
    'Doub', 'Ldoub', 'Fcomp', 'Comp', 'Lcomp';}
    {'Vec', 'Char', 'Int', 'Llong', 'Long', 'Fdoub', ...
    'Doub', 'Ldoub', 'Fcomp', 'Comp', 'Lcomp';}
    {'Mat', 'Char', 'Int', 'Llong', 'Long', 'Fdoub', ...
    'Doub', 'Ldoub', 'Fcomp', 'Comp', 'Lcomp';}
    {'Mat3', 'Char', 'Int', 'Llong', 'Long', 'Fdoub', ...
    'Doub', 'Ldoub', 'Fcomp', 'Comp', 'Lcomp';}
    {'Cmat', 'Char', 'Int', 'Llong', 'Long', 'Fdoub', ...
    'Doub', 'Ldoub', 'Fcomp', 'Comp', 'Lcomp';}
    {'Cmat3', 'Char', 'Int', 'Llong', 'Long', 'Fdoub', ...
    'Doub', 'Ldoub', 'Fcomp', 'Comp', 'Lcomp';}
    {'Cmat4', 'Char', 'Int', 'Llong', 'Long', 'Fdoub', ...
    'Doub', 'Ldoub', 'Fcomp', 'Comp', 'Lcomp';}
    {'Svec', 'Char', 'Int', 'Llong', 'Long', 'Fdoub', ...
    'Doub', 'Ldoub', 'Fcomp', 'Comp', 'Lcomp';}
    {'Dvec', 'Char', 'Int', 'Llong', 'Long', 'Fdoub', ...
    'Doub', 'Ldoub', 'Fcomp', 'Comp', 'Lcomp';}
    {'Scmat', 'Char', 'Int', 'Llong', 'Long', 'Fdoub', ...
    'Doub', 'Ldoub', 'Fcomp', 'Comp', 'Lcomp';}
    {'Dcmat', 'Char', 'Int', 'Llong', 'Long', 'Fdoub', ...
    'Doub', 'Ldoub', 'Fcomp', 'Comp', 'Lcomp';}
    {'Diag', 'Char', 'Int', 'Llong', 'Long', 'Fdoub', ...
    'Doub', 'Ldoub', 'Fcomp', 'Comp', 'Lcomp';}
    };

N = size(type, 1);
code = cell(0);
for i = 1:N
    code{i} = [preproc(file, type{i}{:}), newline];
end
str = [code{:}];
filewrite('../SLISC/global_contain_typedef.inl', str);
